{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}
    role: metrics
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.port }}
      targetPort: {{ .Values.metricsService.port }}
{{- end }}
