{
 "title": "Load Generator  <-> Demo API v2",
 "refresh": "5s",
 "panels": [
  {
   "title": "Loadgen RPS ",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(loadgen_requests_total[30s])",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Loadgen p95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(loadgen_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Demo API p95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(realapp_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(demoapp_http_requests_total{status_class=\"5xx\"}[1m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Target Reachable",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 6 },
   "targets": [
    { "expr": "loadgen_target_up", "legendFormat": "up" }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 16, "w": 18, "h": 6 },
   "targets": [
    { "expr": "realapp_http_inflight_requests", "legendFormat": "inflight" }
   ]
  }
 ]
}