apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: load-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TARGET_URL
              value: {{ .Values.env.targetUrl | quote }}
            - name: CONCURRENCY
              value: {{ .Values.env.concurrency | quote }}
            - name: SLEEP_MS
              value: {{ .Values.env.sleepMs | quote }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
