apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}
    role: metrics
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
