apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-demo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayuspoudel/sentinel-playground
    targetRevision: develop
    path: helm/load-generator
    helm:
      valueFiles: 
        - ../../api-values/values-load-generator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true 
