replicaCount: 1
image:
  repository: ayuspoudel/load-generator
  tag: "1.0.2"
  pullPolicy: IfNotPresent
env:
  targetUrl: "http://demo-api:8080"
  concurrency: "30"
  sleepMs: "20"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi
