# How many pods to run
replicaCount: 2
# Container image configuration
image:
  repository: ayuspoudel/demo-api
  tag: 1.0.3
  pullPolicy: IfNotPresent
# API Service (external access via minikube)
service:
  enabled: true
  type: NodePort
  port: 8080
  nodePort: 30080
# Metrics Service (internal only, for Prometheus)
metricsService:
  enabled: true
  port: 8080
# Environment variables passed to the app
env:
  appName: demoapp
  deploymentName: demoapp
  clusterName: minikube
  errorRate: "0.1"
# Prometheus ServiceMonitor configuration
serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
