apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./applications/sentinel-demo-api.yaml
  - ./prometheus/prometheus-app.yaml
  - ./applications/sentinel-load-generator.yaml

