replicaCount: 1

image:
  repository: ayuspoudel/load-generator
  tag: "1.0.0"
  pullPolicy: IfNotPresent

env:
  targetUrl: "http://demo-api:8080"
  concurrency: "0"
  sleepMs: "0"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi
serviceMonitor:
  enabled: false