replicaCount: 1

image:
  repository: ayuspoudel/load-generator
  tag: "1.0.2"
  pullPolicy: IfNotPresent

env:
  TARGET_URL: "http://demo-api:8080"
  CONCURRENCY: "30"
  SLEEP_MS: "20"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi

serviceMonitor:
  enabled: true
