name: Load Generator CI/CD
run-name: Load Generator CI/CD - ${{ github.actor }}

on:
  push:
    branches: [ develop ]
    paths:
      - "load-generator/*"
      - "api-values/values-load-generator.yaml"
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}

    steps:
      - name: Checkout (detect)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect load generator changes
        id: detect
        run: |
          if git diff --name-only HEAD~1 | grep -q '^load-generator/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  release:
    needs: detect
    if: needs.detect.outputs.changed == 'true'
    runs-on: ubuntu-latest

    env:
      APP_NAME: load-generator
      VALUES_FILE: api-values/values-load-generator.yaml

    steps:
      - name: Checkout (release)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read current version
        id: version
        run: |
          CURRENT=$(yq e '.image.tag' $VALUES_FILE)

          if [ -z "$CURRENT" ] || [ "$CURRENT" = "null" ]; then
            echo "ERROR: Missing image.tag in values.yaml"
            exit 1
          fi

          echo "Current version: $CURRENT"
          echo "current=$CURRENT" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          IFS='.' read -r M m p <<< "${{ steps.version.outputs.current }}"
          NEW="$M.$m.$((p+1))"

          echo "New version: $NEW"
          echo "new=$NEW" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/load-generator:${{ steps.bump.outputs.new }}"

          echo "Building $IMAGE"
          docker build -t "$IMAGE" ./load-generator

          echo "Pushing $IMAGE"
          docker push "$IMAGE"

      - name: Write change artifact
        run: |
          mkdir -p changes
          jq -n --arg version "${{ steps.bump.outputs.new }}" '{version: $version}' > changes/load-generator.json

      - name: Upload change artifact
        uses: actions/upload-artifact@v4
        with:
          name: load-generator-change
          path: changes/

  gitops:
    needs: release
    runs-on: ubuntu-latest

    env:
      VALUES_FILE: api-values/values-load-generator.yaml

    steps:
      - name: Checkout (gitops)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          fetch-depth: 0

      - name: Download change artifact
        uses: actions/download-artifact@v4
        with:
          name: load-generator-change
          path: changes

      - name: Apply GitOps changes
        run: |
          VERSION=$(jq -r '.version' changes/load-generator.json)
          echo "Updating load generator -> $VERSION"
          yq -i ".image.tag = \"${VERSION}\"" $VALUES_FILE

      - name: Commit & push
        run: |
            if git diff --quiet; then
            echo "No GitOps changes detected"
            exit 0
            fi
            git config user.name "sentinel-ci"
            git config user.email "sentinel-ci@users.noreply.github.com"
            git add "$VALUES_FILE"
            git commit -m "gitops: update load generator image [skip ci]"
            git fetch origin develop
            git rebase origin/develop
            git push --force-with-lease origin develop
  

